nodes:
  - "idagpu-18"

run_name: "benchmark-new-network"

useEmptyDir: false
fioPvcName: "fio-test"
dataDir: "100_data"
fileSize: "100G"
iterations: 5
probe_node: false
#helm install fio-bench . -n pgr24james -f values.yaml

